---
- name: Vector | create directory 4install
  ansible.builtin.file:
    path: /tmp/vector
    state: directory
    mode: "755"
- name: Vector | get archive
  ansible.builtin.get_url:
    url: https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-x86_64-unknown-linux-musl.tar.gz
    dest: /tmp/vector/vector-{{ vector_version }}.tar.gz
    mode: "775"
- name: Vector | unarchive
  ansible.builtin.unarchive:
    remote_src: true
    src: "/tmp/vector/vector-{{ vector_version }}.tar.gz"
    dest: /tmp/vector
    extra_opts: [--strip-components=2]
- name: Vector | Create group
  become: true
  ansible.builtin.group:
    name: "{{ vector_group }}"
    state: present
- name: Vector | create user
  become: true
  ansible.builtin.user:
    name: "{{ vector_user }}"
    groups: "{{ vector_group }}"
    state: present
- name: Vector | copy bin file
  become: true
  ansible.builtin.copy:
    remote_src: true
    src: /tmp/vector/bin/vector
    dest: /usr/bin
    mode: "755"
    owner: "{{ vector_user }}"
    group: "{{ vector_group }}"
- name: Vector | create dir on etc
  become: true
  ansible.builtin.file:
    path: "{{ vector_dir }}"
    state: directory
    owner: "{{ vector_user }}"
    group: "{{ vector_group }}"
    mode: "755"
- name: Vector | copy conf
  become: true
  ansible.builtin.template:
    src: template/vector.toml.j2
    dest: "{{ vector_dir }}/vector.toml"
    owner: "{{ vector_user }}"
    group: "{{ vector_group }}"
    mode: "755"
- name: Vector | create dir on lib
  become: true
  ansible.builtin.file:
    path: "{{ vector_data_dir }}"
    state: directory
    owner: "{{ vector_user }}"
    group: "{{ vector_group }}"
    mode: "755"
- name: Vector | copy service file
  become: true
  ansible.builtin.copy:
    remote_src: true
    src: /tmp/vector/etc/systemd/vector.service
    dest: /usr/lib/systemd/system
    mode: "644"
- name: Vector | Start service
  become: true
  ansible.builtin.service:
    name: vector
    state: started
