---
# tasks file for nginx
---
- name: Установка Nginx
  become: yes

  tasks:
    - name: Обновить кэш пакетов
      yum:
        name: '*'
        state: latest
      when: ansible_distribution == 'CentOS'

    - name: Установить Nginx
      yum:
        name: nginx
        state: present
      when: ansible_distribution == 'CentOS'

    - name: Запустить сервис Nginx
      service:
        name: nginx
        state: started
        enabled: yes
